server-name smartdns
bind [::]:6053
cache-size 4194304
cache-persist yes
cache-file /etc/smartdns/smartdns.cache
edns-client-subnet 110.50.80.0/24
tcp-idle-time 60
rr-ttl 60
rr-ttl-min 30
local-ttl 60
rr-ttl-reply-max 60
rr-ttl-max 300
max-reply-ip-num 8
log-level warn
log-file /etc/smartdns/smartdns.log
log-size 128K
log-num 8
log-file-mode 644
audit-enable yes
audit-file /etc/smartdns/smartdns-audit.log
audit-size 128K
audit-num 2
audit-file-mode 644
# Google DNS
server-tls 8.8.8.8
#server-tls 8.8.4.4
server-tls 2001:4860:4860::8888
#server-tls 2001:4860:4860::8844
# Quad9 DNS
server-tls 9.9.9.11
#server-tls 149.112.112.11
server-tls 2620:fe::11
#server-tls 2620:fe::fe:11
# OpenDNS
server-tls 208.67.220.2
#server-tls 208.67.222.2
server-tls 2620:0:ccd::2
#server-tls 2620:0:ccc::2
# Local DNS (Unbound)
#server 127.0.0.1:5353
speed-check-mode ping
#response-mode fastest-response
response-mode fastest-ip
#dns64 64:ff9b::/96
prefetch-domain yes
dualstack-ip-selection yes
dualstack-ip-selection-threshold 10

### Static Address ###
conf-file /etc/smartdns/static-address.conf
